version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: gramcare_db
    environment:
      POSTGRES_DB: gramcare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: gramcare_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=gramcare
      - DB_USER=postgres
      - DB_PASS=postgres
      - JWT_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - NVIDIA_API_KEY=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
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
